### ISSUE TITLE
clearfix is in trumps ?

### ISSUE THREAD

**Issue by sotayamashita** [inuitcss/trumps.clearfix#10]
For example, when I use stylus, I import files according to ITCSS and I try to use `@extend .cf` in `components/_header-nav` but it will not work because `.cf` is not imported before `components/_header-nav`. I think clearfix should be in `tools`. What do you think ?

File structure:

```
.
├── main.styl
└── stylus
    ├── components
    │   └── _header-nav.styl
    └── trumps
        └── _clearfix.styl
```

**Comment by csshugs** [comment]
@sotayamashita 
I don't know Stylus, but in Sass it definitely doesn't matter if `.cf` is imported before or after `components/_header-nav`. However, it's been discussed in #8 if it would be better to provide a mixin for clearfix in the `tools` layer like you proposed so we don't need to use `@extend` anymore.

If Stylus doesn't allow extending a class that's imported later on in the stylesheet, I'm afraid we have to blame Stylus for that. Inuit is written in Sass where this is possible.

So when you want to use the `.cf` class in your markup, the `trumps` layer is the right place for that ([and ideally should have `!important`](https://github.com/inuitcss/trumps.clearfix/issues/6)). But if you want to `@extend` that class anywhere in your stylesheet, it would be better to have a mixin in the `tools` layer and use the mixin instead of `@extend`. That's what's been discussed in #8 by the way.

**Comment by sotayamashita** [comment]
@csshugs Thank you kindly answer. I will look at #8
